batch_size: 8
iters: 50000

train_dataset:
  type: Dataset
  dataset_root: ./1500dataset
  train_path: ./1500dataset/train.txt
  num_classes: 16
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ./1500dataset
  val_path: ./1500dataset/val.txt
  num_classes: 16
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: [0.1, 0.7, 5, 2.8, 1, 1, 0.5, 0.32, 0.9, 1.3, 1.6, 3.3, 0.75, 1, 1, 1]
        - type: LovaszSoftmaxLoss
        - type: AffinityLoss
          num_classes: 16
          init_step : 0
          max_iter: 80000
      coef: [0.4, 0.2, 0.4]
  coef: [1]

# distill_loss is used for distillation
distill_loss:
  types:
    - type: KLLoss
  coef: [3]

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 16
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: Null
