metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  name: VOCDataSet
  dataset_dir: dataset/dataset-voc
  anno_path: train_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: dataset/dataset-voc
  anno_path: test_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: dataset/dataset-voc/labels.txt
